version: "3.8"
services:
  database:
    image: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - app-network
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - .:/app
    ports:
      - "${WEB_SERVER_PORT}:${WEB_SERVER_PORT}"
    networks:
      - app-network
volumes:
  db:

networks:
  app-network:
    driver: bridge