// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type User struct {
	ID                int32        `json:"id"`
	Serial            string       `json:"serial"`
	Name              string       `json:"name"`
	Surname           string       `json:"surname"`
	Email             string       `json:"email"`
	Password          string       `json:"password"`
	TermsAndPrivacyAt sql.NullTime `json:"terms_and_privacy_at"`
	CreatedAt         time.Time    `json:"created_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
}
